# Generated by Django 3.1.2 on 2020-12-20 06:15

# This migration file do nothing and kept for backwards compatibility only.
# Users are advised to manually delete this migration file.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_monitoring', '0001_squashed_0002_devicemonitoring'),
    ]

    operations = [
        migrations.RunPython(
            migrations.RunPython.noop, reverse_code=migrations.RunPython.noop
        )
    ]
